Ruby on Rails capstone project - Budget app
denisdiaconu/Budget-App pull request #5
Opened 2021-11-25 17:11 UTC by denisdiaconu

I created a Ruby on Rails application that allows the user to:

-    register and log in, so that the data is private to them.
-    introduce new transactions associated with a category.
-    see the money spent on each category.

2021-11-25 18:42 UTC, Emmyn5600 requested changes
Hi, @denisdiaconu 

Good job so far! 👏🏼 

- Your project is running successfully.
- You have completed almost all requirements.
- Database is well structured.
- No linter errors
- You have a descriptive Readme file

Great work on making the project requirements:clap:
You've done well implementing the project requirements, but there are still some issues which aren't been addressed yet 
 
## STATUS: CHANGES REQUESTED :recycle:

### Changes requested.

- [ ] Check the comment under the review.

 #### Optional suggestions
 
 - N/A
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2021-11-25 18:42 UTC, Emmyn5600 commented on app/views/entities/_form.html.erb
> +
- [ ]  We don't need to add any logic inside the .erb file, we use the helper folders to create methods with logic and called inside the .erb file. You can refer to this comment to modify the files that have logic inside the .erb file.

Read [this](https://www.toptal.com/ruby-on-rails/top-10-mistakes-that-rails-programmers-make) for more information

2021-11-25 18:42 UTC, Emmyn5600 commented on app/views/groups/_form.html.erb
> +  <% end %>
- [ ]  We don't need to add any logic inside the .erb file, we use the helper folders to create methods with logic and called inside the .erb file. You can refer to this comment to modify the files that have logic inside the .erb file.

Read [this](https://www.toptal.com/ruby-on-rails/top-10-mistakes-that-rails-programmers-make) for more information

2021-11-25 18:42 UTC, Emmyn5600 commented on app/views/shared/_msg.html.erb
> +<% end  %>
- [ ]  We don't need to add any logic inside the .erb file, we use the helper folders to create methods with logic and called inside the .erb file. You can refer to this comment to modify the files that have logic inside the .erb file.

Read [this](https://www.toptal.com/ruby-on-rails/top-10-mistakes-that-rails-programmers-make) for more information

2021-11-25 18:42 UTC, Emmyn5600 commented on test/controllers/entities_controller_test.rb
> +end
- [ ] Optional suggetions 

You have used `minitest` for testing cases, however, you would have used `rspec`, kindly provide clear information in the readme file related to how to run the tests.

2021-11-25 18:42 UTC, Emmyn5600 commented on app/controllers/groups_controller.rb
> +  end
- [ ]  You should avoid making SQL queries outside of models. It makes it harder to test and debug your app.

2021-11-26 13:22 UTC, descholar-ceo approved these changes
Hi @denisdiaconu , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have only 3 code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-11-26 15:51 UTC, merged